
import { RootProvider } from 'fumadocs-ui/provider'
import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import { ReactNode } from 'react'

import { cn } from '@/lib/utils'
import '@/styles/globals.css'

export const metadata: Metadata = {
	title: 'NestJS Monobank',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang='ru' suppressHydrationWarning>
			<body className={cn(GeistSans.variable)}>
   			<RootProvider
  				i18n={{
   					locale: 'uk',
   					translations: {
  						search: 'Пошук',
  						searchNoResult: 'Нічого не знайдено',
        	  	toc: 'На цій сторінці'
   					}
          }}
        >
					{children}
				</RootProvider>
			</body>
		</html>
	)
}
