// @ts-nocheck -- skip type checking
import * as meta_0 from "../src/content/docs/meta.json?collection=meta&hash=1748293774185"
import * as docs_12 from "../src/content/docs/payments/receipts.mdx?collection=docs&hash=1748293774185"
import * as docs_11 from "../src/content/docs/payments/invoice-status.mdx?collection=docs&hash=1748293774185"
import * as docs_10 from "../src/content/docs/payments/get-card-token.mdx?collection=docs&hash=1748293774185"
import * as docs_9 from "../src/content/docs/payments/delete-card-token.mdx?collection=docs&hash=1748293774185"
import * as docs_8 from "../src/content/docs/payments/create-payment-token.mdx?collection=docs&hash=1748293774185"
import * as docs_7 from "../src/content/docs/payments/create-invoice.mdx?collection=docs&hash=1748293774185"
import * as docs_6 from "../src/content/docs/payments/complete-hold.mdx?collection=docs&hash=1748293774185"
import * as docs_5 from "../src/content/docs/refunds/refund-payment.mdx?collection=docs&hash=1748293774185"
import * as docs_4 from "../src/content/docs/refunds/cancel-payment.mdx?collection=docs&hash=1748293774185"
import * as docs_3 from "../src/content/docs/operations/statement.mdx?collection=docs&hash=1748293774185"
import * as docs_2 from "../src/content/docs/merchant/info.mdx?collection=docs&hash=1748293774185"
import * as docs_1 from "../src/content/docs/getting-started/introduction.mdx?collection=docs&hash=1748293774185"
import * as docs_0 from "../src/content/docs/getting-started/installation.mdx?collection=docs&hash=1748293774185"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"getting-started/installation.mdx","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/getting-started/installation.mdx"}, data: docs_0 }, { info: {"path":"getting-started/introduction.mdx","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/getting-started/introduction.mdx"}, data: docs_1 }, { info: {"path":"merchant/info.mdx","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/merchant/info.mdx"}, data: docs_2 }, { info: {"path":"operations/statement.mdx","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/operations/statement.mdx"}, data: docs_3 }, { info: {"path":"refunds/cancel-payment.mdx","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/refunds/cancel-payment.mdx"}, data: docs_4 }, { info: {"path":"refunds/refund-payment.mdx","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/refunds/refund-payment.mdx"}, data: docs_5 }, { info: {"path":"payments/complete-hold.mdx","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/payments/complete-hold.mdx"}, data: docs_6 }, { info: {"path":"payments/create-invoice.mdx","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/payments/create-invoice.mdx"}, data: docs_7 }, { info: {"path":"payments/create-payment-token.mdx","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/payments/create-payment-token.mdx"}, data: docs_8 }, { info: {"path":"payments/delete-card-token.mdx","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/payments/delete-card-token.mdx"}, data: docs_9 }, { info: {"path":"payments/get-card-token.mdx","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/payments/get-card-token.mdx"}, data: docs_10 }, { info: {"path":"payments/invoice-status.mdx","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/payments/invoice-status.mdx"}, data: docs_11 }, { info: {"path":"payments/receipts.mdx","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/payments/receipts.mdx"}, data: docs_12 }]);
export const meta = _runtime.meta<typeof _source.meta>([{ info: {"path":"meta.json","absolutePath":"/Users/arturdocenko/Documents/GitHub/nestjs-monobank/apps/www/src/content/docs/meta.json"}, data: meta_0 }]);